[project]
name = "excel-format"
version = "0.1.0"
description = "A Python tool for batch formatting Excel workbooks with conditional styling, data validation, and worksheet protection"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.0",
]